export default {
  autoInstall: {},
  alias: {
    full: 'local:full',
    'exit-full': 'local:exit-full',
    loading: 'local:loading-three',
    switch: 'local:action-center',
    apple: 'simple-icons:apple',
    bing: 'simple-icons:microsoftbing',
    google: 'simple-icons:google',
    baidu: 'simple-icons:baidu',
    yahoo: 'simple-icons:yahoo',
    wikipedia: 'simple-icons:wikipedia',
    qwant: 'simple-icons:quora',
    windows: 'mdi:microsoft-windows',
    system: 'local:system',
    light: 'mdi:white-balance-sunny',
    dark: 'mdi:weather-night',
    check: 'mdi:check',
    close: 'mdi:window-close',
    minus: 'mdi:window-minimize',
  },
  include: [
    'simple-icons:apple',
    'simple-icons:microsoftbing',
    'simple-icons:google',
    'simple-icons:baidu',
    'simple-icons:yahoo',
    'simple-icons:wikipedia',
    'simple-icons:quora',
    'mdi:microsoft-windows',
    'mdi:white-balance-sunny',
    'mdi:weather-night',
    'mdi:check',
    'mdi:window-close',
    'mdi:window-minimize',
    'local:system',
    'local:action-center',
    'local:full',
    'local:exit-full',
  ],
};
